//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DictionaryEntityFw
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary
    {
        public int WordID { get; set; }
        public string Word { get; set; }
        public System.DateTime EditDate { get; set; }
        public string Meaning { get; set; }
        public int ID { get; set; }
    
        public virtual WordType WordType { get; set; }
    }
}
